spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/phonelines
    username: root
    password:



#spring:
#  datasource:
#    url:  jdbc:mysql://db4free.net:3306/basedatosutn
#    username: lalolipc
#    password: chocolate
#  jpa:
#    show-sql: true
#    hibernate:
#    ddl-auto: create-drop

#spring:
#  datasource:
#    url:  jdbc:mysql://tpip.ddns.net:3306/tp_avanzada_1
#    username: rocio
#    password: 123

#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

#  jpa:
#    show-sql: true
#    hibernate:
#    ddl-auto: create-drop




